version: "3.9"

networks: 
  happymovie-net:
    name: happymovie-net

services: 

  happymovie-web:
    container_name: happymovie-web
    image: happymovie-web
    ports: 
      - "8080:80"
    networks: 
      - happymovie-net

  
  happymovie-server:
    container_name: happymovie-server
    image: happymovie-server
    ports: 
      - "5000:80"
    networks:
      - happymovie-net

  happymovie-db:
    container_name: happymovie-db
    image: mysql:8.0.27
    volumes:
      - "happymovie-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: happymovie1234
      MYSQL_DATABASE: happymovie
    networks:
      - happymovie-net


volumes:
  happymovie-data:
